(load "simulator.scm")

(define (make-save inst machine stack pc)
  (let* ((reg-name (stack-inst-reg-name inst))
         (reg (get-register machine reg-name)))
    (lambda ()
      (push stack (cons reg-name (get-contents reg)))
      (advance-pc pc))))
(define (make-restore inst machine stack pc)
  (let* ((reg-name (stack-inst-reg-name inst))
         (reg (get-register machine reg-name)))
    (lambda ()
      (let ((top (pop stack)))
        (if (eq? (car top) reg-name)
            (begin (set-contents! reg (cdr top))
                   (advance-pc pc))
            (error "No matched name: STACK" reg-name))))))
